// ============================================================================
// RECIPE CATALOG
// The single source of truth the whole prototype computes against:
// insight counts ("we've hidden 12 recipes"), the plan engine, and the
// edge cases all read from this list. 32 recipes, deliberately balanced so
// that certain answer combos produce sparse or special results.
// ============================================================================

export type Base = "meat" | "poultry" | "fish" | "vegetarian" | "vegan";
export type Allergen = "gluten" | "dairy" | "nuts" | "shellfish" | "soy" | "eggs";
export type MealType = "breakfast" | "lunch" | "dinner";
/** Divisive ingredients the "not for you" question can filter on. */
export type FlavourTag = "mushrooms" | "olives" | "coriander" | "tofu";
export type Cuisine =
  | "italian"
  | "mexican"
  | "asian"
  | "mediterranean"
  | "indian"
  | "american";

export interface Recipe {
  id: string;
  name: string;
  description: string;
  emoji: string;
  base: Base;
  cuisine: Cuisine;
  allergens: Allergen[];
  proteinGrams: number;
  minutes: number;
  spiceLevel: 0 | 1 | 2 | 3;
  kidFriendly: boolean;
  /** Defaults to "dinner" when omitted (the original catalogue is all dinners). */
  mealType?: MealType;
  /** Divisive ingredients this recipe features (see the "icks" question). */
  flavourTags?: FlavourTag[];
}

export function mealTypeOf(recipe: Recipe): MealType {
  return recipe.mealType ?? "dinner";
}

export const MEAL_TYPE_LABELS: Record<MealType, string> = {
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
};

export const CUISINE_LABELS: Record<Cuisine, string> = {
  italian: "Italian",
  mexican: "Mexican",
  asian: "Asian",
  mediterranean: "Mediterranean",
  indian: "Indian",
  american: "American",
};

export const ALLERGEN_LABELS: Record<Allergen, string> = {
  gluten: "gluten",
  dairy: "dairy",
  nuts: "nuts",
  shellfish: "shellfish",
  soy: "soy",
  eggs: "eggs",
};

export const recipes: Recipe[] = [
  // --- Vegan (8) ---
  {
    id: "chili-tofu-stirfry",
    name: "Crispy Chilli Tofu Stir-Fry",
    description: "Golden tofu tossed with peppers in a sticky chilli glaze",
    emoji: "🌶️",
    base: "vegan",
    cuisine: "asian",
    allergens: ["soy", "gluten"],
    proteinGrams: 24,
    minutes: 25,
    spiceLevel: 2,
    kidFriendly: false,
    flavourTags: ["tofu"],
  },
  {
    id: "black-bean-tacos",
    name: "Smoky Black Bean Tacos",
    description: "Charred corn tortillas with smoky beans and lime slaw",
    emoji: "🌮",
    base: "vegan",
    cuisine: "mexican",
    allergens: [],
    proteinGrams: 15,
    minutes: 20,
    spiceLevel: 1,
    kidFriendly: true,
    flavourTags: ["coriander"],
  },
  {
    id: "peanut-noodles",
    name: "Peanut Noodle Bowl",
    description: "Springy noodles in a silky peanut-lime sauce",
    emoji: "🥜",
    base: "vegan",
    cuisine: "asian",
    allergens: ["nuts", "gluten", "soy"],
    proteinGrams: 18,
    minutes: 20,
    spiceLevel: 2,
    kidFriendly: false,
  },
  {
    id: "lentil-bolognese",
    name: "Lentil Bolognese",
    description: "Slow-simmered lentil ragù over ribbons of pappardelle",
    emoji: "🍝",
    base: "vegan",
    cuisine: "italian",
    allergens: ["gluten"],
    proteinGrams: 21,
    minutes: 35,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "chickpea-curry",
    name: "Chickpea Coconut Curry",
    description: "Creamy coconut curry with spinach and toasted cumin",
    emoji: "🍛",
    base: "vegan",
    cuisine: "indian",
    allergens: [],
    proteinGrams: 16,
    minutes: 30,
    spiceLevel: 2,
    kidFriendly: false,
    flavourTags: ["coriander"],
  },
  {
    id: "bbq-tempeh-bowl",
    name: "BBQ Tempeh Power Bowl",
    description: "Sticky BBQ tempeh over rice with charred sweetcorn",
    emoji: "🍚",
    base: "vegan",
    cuisine: "american",
    allergens: ["soy"],
    proteinGrams: 28,
    minutes: 30,
    spiceLevel: 1,
    kidFriendly: false,
  },
  {
    id: "seitan-fajitas",
    name: "Sizzling Seitan Fajitas",
    description: "Pan-seared seitan strips with blistered peppers",
    emoji: "🫑",
    base: "vegan",
    cuisine: "mexican",
    allergens: ["gluten", "soy"],
    proteinGrams: 30,
    minutes: 25,
    spiceLevel: 2,
    kidFriendly: false,
    flavourTags: ["coriander"],
  },
  {
    id: "quinoa-veg-salad",
    name: "Roasted Veg & Quinoa Salad",
    description: "Harissa-roasted veg with herby quinoa and toasted seeds",
    emoji: "🥗",
    base: "vegan",
    cuisine: "mediterranean",
    allergens: [],
    proteinGrams: 14,
    minutes: 25,
    spiceLevel: 0,
    kidFriendly: false,
    flavourTags: ["olives"],
  },

  // --- Vegetarian (6) ---
  {
    id: "halloumi-burgers",
    name: "Crispy Halloumi Burgers",
    description: "Golden halloumi with harissa mayo in a brioche bun",
    emoji: "🍔",
    base: "vegetarian",
    cuisine: "american",
    allergens: ["dairy", "gluten"],
    proteinGrams: 22,
    minutes: 20,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "paneer-tikka",
    name: "Paneer Tikka Masala",
    description: "Charred paneer in a rich, gently spiced tomato sauce",
    emoji: "🧀",
    base: "vegetarian",
    cuisine: "indian",
    allergens: ["dairy"],
    proteinGrams: 25,
    minutes: 35,
    spiceLevel: 2,
    kidFriendly: false,
  },
  {
    id: "caprese-gnocchi",
    name: "Caprese Gnocchi Bake",
    description: "Pillowy gnocchi baked with mozzarella and basil",
    emoji: "🍅",
    base: "vegetarian",
    cuisine: "italian",
    allergens: ["dairy", "gluten"],
    proteinGrams: 18,
    minutes: 30,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "bean-quesadillas",
    name: "Black Bean Quesadillas",
    description: "Melty cheddar and beans in crisp folded tortillas",
    emoji: "🫓",
    base: "vegetarian",
    cuisine: "mexican",
    allergens: ["dairy", "gluten"],
    proteinGrams: 20,
    minutes: 15,
    spiceLevel: 1,
    kidFriendly: true,
  },
  {
    id: "shakshuka",
    name: "Shakshuka with Feta",
    description: "Eggs poached in spiced tomatoes with crumbled feta",
    emoji: "🍳",
    base: "vegetarian",
    cuisine: "mediterranean",
    allergens: ["eggs", "dairy"],
    proteinGrams: 19,
    minutes: 25,
    spiceLevel: 1,
    kidFriendly: false,
  },
  {
    id: "mushroom-risotto",
    name: "Wild Mushroom Risotto",
    description: "Slow-stirred risotto with porcini and parmesan",
    emoji: "🍄",
    base: "vegetarian",
    cuisine: "italian",
    allergens: ["dairy"],
    proteinGrams: 12,
    minutes: 40,
    spiceLevel: 0,
    kidFriendly: false,
    flavourTags: ["mushrooms"],
  },

  // --- Fish & seafood (5) ---
  {
    id: "miso-salmon",
    name: "Miso-Glazed Salmon",
    description: "Caramelised miso salmon with sesame greens",
    emoji: "🐟",
    base: "fish",
    cuisine: "asian",
    allergens: ["soy"],
    proteinGrams: 34,
    minutes: 25,
    spiceLevel: 0,
    kidFriendly: false,
  },
  {
    id: "shrimp-linguine",
    name: "Garlic Shrimp Linguine",
    description: "Juicy prawns in a garlic-butter white wine sauce",
    emoji: "🦐",
    base: "fish",
    cuisine: "italian",
    allergens: ["shellfish", "gluten"],
    proteinGrams: 28,
    minutes: 25,
    spiceLevel: 1,
    kidFriendly: false,
  },
  {
    id: "fish-tacos",
    name: "Baja Fish Tacos",
    description: "Crispy white fish with lime crema and pickled onion",
    emoji: "🐠",
    base: "fish",
    cuisine: "mexican",
    allergens: ["gluten", "dairy"],
    proteinGrams: 26,
    minutes: 25,
    spiceLevel: 1,
    kidFriendly: true,
    flavourTags: ["coriander"],
  },
  {
    id: "lemon-cod",
    name: "Lemon Herb Cod & Crushed Potatoes",
    description: "Flaky cod with buttery herbed potatoes",
    emoji: "🍋",
    base: "fish",
    cuisine: "mediterranean",
    allergens: [],
    proteinGrams: 30,
    minutes: 30,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "tuna-poke",
    name: "Tuna Poke Bowl",
    description: "Marinated tuna over sushi rice with avocado",
    emoji: "🍣",
    base: "fish",
    cuisine: "asian",
    allergens: ["soy"],
    proteinGrams: 32,
    minutes: 15,
    spiceLevel: 1,
    kidFriendly: false,
    flavourTags: ["coriander"],
  },

  // --- Poultry (7) ---
  {
    id: "honey-garlic-chicken",
    name: "Honey Garlic Chicken Thighs",
    description: "Sticky glazed thighs with steamed jasmine rice",
    emoji: "🍗",
    base: "poultry",
    cuisine: "asian",
    allergens: ["soy"],
    proteinGrams: 38,
    minutes: 30,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "chicken-burrito-bowl",
    name: "Chicken Burrito Bowls",
    description: "Chipotle chicken with rice, beans and pico de gallo",
    emoji: "🥣",
    base: "poultry",
    cuisine: "mexican",
    allergens: ["dairy"],
    proteinGrams: 36,
    minutes: 25,
    spiceLevel: 1,
    kidFriendly: true,
  },
  {
    id: "tuscan-chicken",
    name: "Creamy Tuscan Chicken",
    description: "Pan chicken in a sundried-tomato cream sauce",
    emoji: "🍗",
    base: "poultry",
    cuisine: "italian",
    allergens: ["dairy"],
    proteinGrams: 40,
    minutes: 30,
    spiceLevel: 0,
    kidFriendly: false,
  },
  {
    id: "chicken-tikka-skewers",
    name: "Chicken Tikka Skewers",
    description: "Yogurt-marinated skewers with cooling raita",
    emoji: "🍢",
    base: "poultry",
    cuisine: "indian",
    allergens: ["dairy"],
    proteinGrams: 35,
    minutes: 30,
    spiceLevel: 2,
    kidFriendly: false,
    flavourTags: ["coriander"],
  },
  {
    id: "chicken-katsu",
    name: "Crispy Chicken Katsu",
    description: "Panko chicken with sweet-savoury curry sauce",
    emoji: "🍛",
    base: "poultry",
    cuisine: "asian",
    allergens: ["gluten", "eggs"],
    proteinGrams: 34,
    minutes: 35,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "greek-chicken-bowl",
    name: "Greek Chicken Bowls",
    description: "Lemon-oregano chicken with tzatziki and olives",
    emoji: "🫒",
    base: "poultry",
    cuisine: "mediterranean",
    allergens: ["dairy"],
    proteinGrams: 37,
    minutes: 25,
    spiceLevel: 0,
    kidFriendly: false,
    flavourTags: ["olives"],
  },
  {
    id: "buffalo-wraps",
    name: "Buffalo Chicken Wraps",
    description: "Fiery buffalo chicken with ranch and crunchy slaw",
    emoji: "🌯",
    base: "poultry",
    cuisine: "american",
    allergens: ["gluten", "dairy"],
    proteinGrams: 33,
    minutes: 15,
    spiceLevel: 2,
    kidFriendly: false,
  },

  // --- Red meat & pork (6) ---
  {
    id: "smash-burgers",
    name: "Classic Beef Smash Burgers",
    description: "Crispy-edged patties with burger sauce and fries",
    emoji: "🍔",
    base: "meat",
    cuisine: "american",
    allergens: ["gluten", "dairy"],
    proteinGrams: 35,
    minutes: 20,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "beef-bibimbap",
    name: "Korean Beef Bibimbap",
    description: "Gochujang beef with quick pickles and a fried egg",
    emoji: "🍳",
    base: "meat",
    cuisine: "asian",
    allergens: ["soy", "eggs"],
    proteinGrams: 32,
    minutes: 30,
    spiceLevel: 2,
    kidFriendly: false,
    flavourTags: ["mushrooms"],
  },
  {
    id: "pork-carnitas",
    name: "Pork Carnitas Tacos",
    description: "Slow-crisped pork with pineapple salsa on corn tortillas",
    emoji: "🌮",
    base: "meat",
    cuisine: "mexican",
    allergens: [],
    proteinGrams: 30,
    minutes: 40,
    spiceLevel: 1,
    kidFriendly: false,
    flavourTags: ["coriander"],
  },
  {
    id: "spaghetti-meatballs",
    name: "Spaghetti & Pork Meatballs",
    description: "Herby meatballs in a rich tomato sugo",
    emoji: "🍝",
    base: "meat",
    cuisine: "italian",
    allergens: ["gluten", "eggs", "dairy"],
    proteinGrams: 31,
    minutes: 35,
    spiceLevel: 0,
    kidFriendly: true,
  },
  {
    id: "steak-fajita-skillet",
    name: "Steak Fajita Skillet",
    description: "Seared steak strips with smoky charred peppers",
    emoji: "🥩",
    base: "meat",
    cuisine: "mexican",
    allergens: [],
    proteinGrams: 38,
    minutes: 25,
    spiceLevel: 2,
    kidFriendly: false,
    flavourTags: ["coriander"],
  },
  {
    id: "lamb-kofta",
    name: "Lamb Kofta with Tzatziki",
    description: "Spiced lamb skewers with flatbread and mint yogurt",
    emoji: "🥙",
    base: "meat",
    cuisine: "mediterranean",
    allergens: ["dairy"],
    proteinGrams: 29,
    minutes: 30,
    spiceLevel: 1,
    kidFriendly: false,
  },

  // ==========================================================================
  // BREAKFASTS (9)
  // ==========================================================================
  {
    id: "berry-overnight-oats",
    name: "Berry Almond Overnight Oats",
    description: "Creamy oats with roasted berries and toasted almonds",
    emoji: "🫐",
    base: "vegan",
    cuisine: "american",
    allergens: ["nuts"],
    proteinGrams: 12,
    minutes: 5,
    spiceLevel: 0,
    kidFriendly: true,
    mealType: "breakfast",
  },
  {
    id: "chia-mango-pudding",
    name: "Coconut Chia Pudding with Mango",
    description: "Silky coconut chia with fresh mango and lime",
    emoji: "🥭",
    base: "vegan",
    cuisine: "asian",
    allergens: [],
    proteinGrams: 8,
    minutes: 5,
    spiceLevel: 0,
    kidFriendly: true,
    mealType: "breakfast",
  },
  {
    id: "green-smoothie-bowl",
    name: "Green Goddess Smoothie Bowl",
    description: "Spinach, banana and almond butter, topped with seeds",
    emoji: "🥬",
    base: "vegan",
    cuisine: "american",
    allergens: ["nuts"],
    proteinGrams: 14,
    minutes: 10,
    spiceLevel: 0,
    kidFriendly: false,
    mealType: "breakfast",
  },
  {
    id: "tofu-scramble",
    name: "Turmeric Tofu Scramble on Toast",
    description: "Golden scrambled tofu with chives on sourdough",
    emoji: "🍞",
    base: "vegan",
    cuisine: "american",
    allergens: ["soy", "gluten"],
    proteinGrams: 20,
    minutes: 15,
    spiceLevel: 0,
    kidFriendly: false,
    flavourTags: ["tofu"],
    mealType: "breakfast",
  },
  {
    id: "yogurt-granola-pots",
    name: "Greek Yogurt & Honey Granola Pots",
    description: "Thick yogurt layered with crunchy granola and honey",
    emoji: "🍯",
    base: "vegetarian",
    cuisine: "mediterranean",
    allergens: ["dairy", "nuts", "gluten"],
    proteinGrams: 18,
    minutes: 5,
    spiceLevel: 0,
    kidFriendly: true,
    mealType: "breakfast",
  },
  {
    id: "spinach-feta-omelette",
    name: "Spinach & Feta Omelette",
    description: "Folded eggs with wilted spinach and salty feta",
    emoji: "🍳",
    base: "vegetarian",
    cuisine: "mediterranean",
    allergens: ["eggs", "dairy"],
    proteinGrams: 22,
    minutes: 10,
    spiceLevel: 0,
    kidFriendly: false,
    mealType: "breakfast",
  },
  {
    id: "banana-pancakes",
    name: "Fluffy Banana Pancakes",
    description: "Stack of banana pancakes with maple syrup",
    emoji: "🥞",
    base: "vegetarian",
    cuisine: "american",
    allergens: ["gluten", "eggs", "dairy"],
    proteinGrams: 12,
    minutes: 20,
    spiceLevel: 0,
    kidFriendly: true,
    mealType: "breakfast",
  },
  {
    id: "salmon-bagels",
    name: "Smoked Salmon Breakfast Bagels",
    description: "Toasted bagels with cream cheese, salmon and dill",
    emoji: "🥯",
    base: "fish",
    cuisine: "american",
    allergens: ["gluten", "dairy"],
    proteinGrams: 24,
    minutes: 10,
    spiceLevel: 0,
    kidFriendly: false,
    mealType: "breakfast",
  },
  {
    id: "breakfast-burritos",
    name: "Chorizo Breakfast Burritos",
    description: "Eggs, chorizo and salsa wrapped in warm tortillas",
    emoji: "🌯",
    base: "meat",
    cuisine: "mexican",
    allergens: ["eggs", "gluten", "dairy"],
    proteinGrams: 26,
    minutes: 20,
    spiceLevel: 1,
    kidFriendly: false,
    mealType: "breakfast",
  },

  // ==========================================================================
  // LUNCHES (8)
  // ==========================================================================
  {
    id: "rainbow-grain-bowl",
    name: "Rainbow Grain Bowl",
    description: "Quinoa, roasted veg and herbs with a lemon dressing",
    emoji: "🌈",
    base: "vegan",
    cuisine: "mediterranean",
    allergens: [],
    proteinGrams: 15,
    minutes: 20,
    spiceLevel: 0,
    kidFriendly: false,
    mealType: "lunch",
  },
  {
    id: "falafel-pitas",
    name: "Falafel Pita Pockets",
    description: "Crispy falafel with pickled cabbage and tahini",
    emoji: "🧆",
    base: "vegan",
    cuisine: "mediterranean",
    allergens: ["gluten"],
    proteinGrams: 16,
    minutes: 20,
    spiceLevel: 1,
    kidFriendly: true,
    mealType: "lunch",
  },
  {
    id: "miso-soba-soup",
    name: "Miso Soba Noodle Soup",
    description: "Umami broth with soba, greens and sesame",
    emoji: "🍜",
    base: "vegan",
    cuisine: "asian",
    allergens: ["soy", "gluten"],
    proteinGrams: 17,
    minutes: 15,
    spiceLevel: 1,
    kidFriendly: false,
    flavourTags: ["mushrooms", "tofu"],
    mealType: "lunch",
  },
  {
    id: "caprese-panini",
    name: "Caprese Panini",
    description: "Pressed mozzarella, tomato and basil on ciabatta",
    emoji: "🥪",
    base: "vegetarian",
    cuisine: "italian",
    allergens: ["dairy", "gluten"],
    proteinGrams: 19,
    minutes: 10,
    spiceLevel: 0,
    kidFriendly: true,
    mealType: "lunch",
  },
  {
    id: "halloumi-quinoa-salad",
    name: "Warm Halloumi & Quinoa Salad",
    description: "Seared halloumi over herby quinoa and greens",
    emoji: "🥗",
    base: "vegetarian",
    cuisine: "mediterranean",
    allergens: ["dairy"],
    proteinGrams: 21,
    minutes: 20,
    spiceLevel: 0,
    kidFriendly: false,
    mealType: "lunch",
  },
  {
    id: "tuna-nicoise",
    name: "Tuna Niçoise Salad",
    description: "Seared tuna, eggs, olives and green beans",
    emoji: "🥗",
    base: "fish",
    cuisine: "mediterranean",
    allergens: ["eggs"],
    proteinGrams: 28,
    minutes: 20,
    spiceLevel: 0,
    kidFriendly: false,
    flavourTags: ["olives"],
    mealType: "lunch",
  },
  {
    id: "chicken-caesar-wraps",
    name: "Chicken Caesar Wraps",
    description: "Grilled chicken, crisp lettuce and parmesan in a wrap",
    emoji: "🌯",
    base: "poultry",
    cuisine: "american",
    allergens: ["gluten", "dairy", "eggs"],
    proteinGrams: 30,
    minutes: 15,
    spiceLevel: 0,
    kidFriendly: true,
    mealType: "lunch",
  },
  {
    id: "steak-chimichurri-salad",
    name: "Steak & Chimichurri Salad",
    description: "Sliced steak over leaves with punchy chimichurri",
    emoji: "🥩",
    base: "meat",
    cuisine: "mexican",
    allergens: [],
    proteinGrams: 32,
    minutes: 25,
    spiceLevel: 1,
    kidFriendly: false,
    mealType: "lunch",
  },
];
